import { NgModule } from '@angular/core';
import { PreloadAllModules, RouterModule, Routes } from '@angular/router';

const routes: Routes = [
  {
    path: '',
    loadChildren: () => import('./tabs/tabs.module').then(m => m.TabsPageModule)
  },
  { path: 'signin', loadChildren: './signin/signin.module#SigninPageModule' },
  { path: 'login', loadChildren: './signin/signin.module#SigninPageModule' },
  { path: 'home', loadChildren: './home/home.module#HomePageModule' },
  { path: 'signup', loadChildren: './signup/signup.module#SignupPageModule' },
  { path: 'forgot', loadChildren: './forgot/forgot.module#ForgotPageModule' },
  { path: 'shop', loadChildren: './shop/shop.module#ShopPageModule' },
  { path: 'shop/:service_id', loadChildren: './shop/shop.module#ShopPageModule' },
  { path: 'shop_search/:q', loadChildren: './shop/shop.module#ShopPageModule' },
  { path: 'shop_search', loadChildren: './shop/shop.module#ShopPageModule' },
  { path: 'barbors', loadChildren: './barbors/barbors.module#BarborsPageModule' },
  { path: 'appointments/:user_id', loadChildren: './appointments/appointments.module#AppointmentsPageModule' },
  { path: 'messages', loadChildren: './messages/messages.module#MessagesPageModule' },
  // { path: 'askquestion', loadChildren: './askquestion/askquestion.module#AskquestionPageModule' }
  { path: 'contact', loadChildren: './contact/contact.module#ContactPageModule' },
  { path: 'news', loadChildren: './news/news.module#NewsPageModule' },
  { path: 'aboutshop', loadChildren: './aboutshop/aboutshop.module#AboutshopPageModule' },
  { path: 'userprofile', loadChildren: './userprofile/userprofile.module#UserprofilePageModule' },
  { path: 'userprofile/:user_id/:type', loadChildren: './userprofile/userprofile.module#UserprofilePageModule' },
  { path: 'about', loadChildren: './about/about.module#AboutPageModule' },
  { path: 'addupload', loadChildren: './addupload/addupload.module#AdduploadPageModule' },
  { path: 'barbercontactinfo', loadChildren: './barbercontactinfo/barbercontactinfo.module#BarbercontactinfoPageModule' },
  { path: 'barberprofile', loadChildren: './barberprofile/barberprofile.module#BarberprofilePageModule' },
  { path: 'barberprofile/:user_id/:type', loadChildren: './barberprofile/barberprofile.module#BarberprofilePageModule' },
  { path: 'invoice', loadChildren: './invoice/invoice.module#InvoicePageModule' },
  { path: 'invoice/:user_id', loadChildren: './invoice/invoice.module#InvoicePageModule' },
  { path: 'chat', loadChildren: './chat/chat.module#ChatPageModule' },
  { path: 'booking', loadChildren: './booking/booking.module#BookingPageModule' },
  { path: 'booking/:booking_type', loadChildren: './booking/booking.module#BookingPageModule' },
  { path: 'booking2', loadChildren: './booking2/booking2.module#Booking2PageModule' },
  { path: 'booking2/:booking_id', loadChildren: './booking2/booking2.module#Booking2PageModule' },
  { path: 'nearby', loadChildren: './nearby/nearby.module#NearbyPageModule' },
  { path: 'services', loadChildren: './services/services.module#ServicesPageModule' },
  { path: 'searchfilter', loadChildren: './searchfilter/searchfilter.module#SearchfilterPageModule' },
  { path: 'managebankcards', loadChildren: './managebankcards/managebankcards.module#ManagebankcardsPageModule' },
  { path: 'choosetype', loadChildren: './choosetype/choosetype.module#ChoosetypePageModule' },
  { path: 'billing', loadChildren: './billing/billing.module#BillingPageModule' },
  { path: 'billing/:type', loadChildren: './billing/billing.module#BillingPageModule' },
  { path: 'billing/:type/:page', loadChildren: './billing/billing.module#BillingPageModule' },
  { path: 'thankyou', loadChildren: './thankyou/thankyou.module#ThankyouPageModule' },
  { path: 'gallery-custom-modal', loadChildren: './gallery-custom-modal/gallery-custom-modal.module#GalleryCustomModalPageModule' },
  { path: 'cardinfo', loadChildren: './cardinfo/cardinfo.module#CardinfoPageModule' },
  { path: 'billingedit/:type/:card_id/:card_last4/:card_brand/:card_exp_month/:card_exp_year/:card_name/edit/:default', loadChildren: './billingedit/billingedit.module#BillingeditPageModule' },
  { path: 'singlefeed/:id', loadChildren: './singlefeed/singlefeed.module#SinglefeedPageModule' },
  { path: 'notifications', loadChildren: './notifications/notifications.module#NotificationsPageModule' },
  { path: 'myservicesadd', loadChildren: './myservicesadd/myservicesadd.module#MyservicesaddPageModule' },
  { path: 'wallet', loadChildren: './wallet/wallet.module#WalletPageModule' },
  { path: 'walletrequest', loadChildren: './walletrequest/walletrequest.module#WalletrequestPageModule' },
  { path: 'check-mail', loadChildren: './check-mail/check-mail.module#CheckMailPageModule' },
  { path: 'forgot-popup', loadChildren: './forgot-popup/forgot-popup.module#ForgotPopupPageModule' },
  { path: 'review', loadChildren: './review/review.module#ReviewPageModule' },
  { path: 'signin-signup', loadChildren: './signin-signup/signin-signup.module#SigninSignupPageModule' },
  { path: 'tutorial', loadChildren: './tutorial/tutorial.module#TutorialPageModule' },
  { path: 'terms', loadChildren: './terms/terms.module#TermsPageModule' },
  { path: 'policy', loadChildren: './policy/policy.module#PolicyPageModule' },
  { path: 'faq', loadChildren: './faq/faq.module#FaqPageModule' },
  { path: 'contact-page', loadChildren: './contact-page/contact-page.module#ContactPagePageModule' },
  { path: 'change-password', loadChildren: './change-password/change-password.module#ChangePasswordPageModule' },
  { path: 'trip-driver', loadChildren: './trip-driver/trip-driver.module#TripDriverPageModule' },
  { path: 'profile-popup', loadChildren: './profile-popup/profile-popup.module#ProfilePopupPageModule' },
  { path: 'background-check', loadChildren: './background-check/background-check.module#BackgroundCheckPageModule' },
  { path: 'background-check-ques', loadChildren: './background-check-ques/background-check-ques.module#BackgroundCheckQuesPageModule' },
  { path: 'document-info', loadChildren: './document-info/document-info.module#DocumentInfoPageModule' },
  { path: 'document-information', loadChildren: './document-information/document-information.module#DocumentInformationPageModule' },
  { path: 'account', loadChildren: './account/account.module#AccountPageModule' },
  { path: 'delivery-info', loadChildren: './delivery-info/delivery-info.module#DeliveryInfoPageModule' },
  { path: 'report-company', loadChildren: './report-company/report-company.module#ReportCompanyPageModule' },
  { path: 'delivery-history', loadChildren: './delivery-history/delivery-history.module#DeliveryHistoryPageModule' },
  { path: 'manage-vehicle', loadChildren: './manage-vehicle/manage-vehicle.module#ManageVehiclePageModule' },
  { path: 'today-history', loadChildren: './today-history/today-history.module#TodayHistoryPageModule' },
  { path: 'home-user', loadChildren: './home-user/home-user.module#HomeUserPageModule' },
  { path: 'schedule-delivery', loadChildren: './schedule-delivery/schedule-delivery.module#ScheduleDeliveryPageModule' },
  { path: 'view-status', loadChildren: './view-status/view-status.module#ViewStatusPageModule' },
  { path: 'vehicle-info', loadChildren: './vehicle-info/vehicle-info.module#VehicleInfoPageModule' },
  { path: 'basic-info', loadChildren: './basic-info/basic-info.module#BasicInfoPageModule' },
  { path: 'update-status', loadChildren: './update-status/update-status.module#UpdateStatusPageModule' },
  { path: 'cards', loadChildren: './cards/cards.module#CardsPageModule' },
  { path: 'basic-information', loadChildren: './basic-information/basic-information.module#BasicInformationPageModule' },
  { path: 'report-driver', loadChildren: './report-driver/report-driver.module#ReportDriverPageModule' },
  { path: 'accepted-delivery', loadChildren: './accepted-delivery/accepted-delivery.module#AcceptedDeliveryPageModule' },
  { path: 'car-info', loadChildren: './car-info/car-info.module#CarInfoPageModule' },
  { path: 'vehicle-information', loadChildren: './vehicle-information/vehicle-information.module#VehicleInformationPageModule' },
  { path: 'add-order-details', loadChildren: './add-order-details/add-order-details.module#AddOrderDetailsPageModule' },
  { path: 'address-info', loadChildren: './address-info/address-info.module#AddressInfoPageModule' },
  { path: 'signupsuccess', loadChildren: './signupsuccess/signupsuccess.module#SignupsuccessPageModule' },
  { path: 'driverselect/:booking_id', loadChildren: './driverselect/driverselect.module#DriverselectPageModule' },
  { path: 'background-check-edit', loadChildren: './background-check-edit/background-check-edit.module#BackgroundCheckEditPageModule' },
  { path: 'make-payment', loadChildren: './make-payment/make-payment.module#MakePaymentPageModule' },
  { path: 'faq-single/:id', loadChildren: './faq-single/faq-single.module#FaqSinglePageModule' },
  { path: 'delivery-history2', loadChildren: './delivery-history2/delivery-history2.module#DeliveryHistory2PageModule' },

];
@NgModule({
  imports: [
    RouterModule.forRoot(routes, { preloadingStrategy: PreloadAllModules })
  ],
  exports: [RouterModule]
})
export class AppRoutingModule {}
